## Advanced indexing and index tricks

### Indexing with Arrays of indices

In [1]:
import numpy as np

a = np.arange(12)**2
i = np.array([1,1,3,8,5])
a[i]

array([ 1,  1,  9, 64, 25])

In [5]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [6]:
j = np.array([[3,4],[9,7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [8]:
palette = np.array([[0,0,0],    # black
                    [255,0,0],  # red
                    [0,255,0],  # green
                    [0,0,255],
                    [255,255,255]]) # blue

image = np.array([[0,1,2,0],
                 [0,3,4,0]])

palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [9]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
i = np.array([[0, 1],   # indices for the first dim of a
              [1, 2]])

j = np.array([[2, 1],   # indices for the second dim
              [3, 3]])

a[i,j] # i and j must have same shape

array([[ 2,  5],
       [ 7, 11]])

In [13]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [14]:
a[:, j] # i.e., a[ : , j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

* In Python, arr[(i,j)] is exactly the same as i[i,j]. So i and j can be put in a tuple for indexing

In [16]:
l = (i, j)
a[l] # same as a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [17]:
# This will not work because it's passing an array, not a tuple.
# This will be interpreted as indexing the first dimension
s = np.array([i, j])
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [18]:
# This is the same as a[i, j]
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

* Search for maximum val of time-dependent series

In [19]:
time = np.linspace(20,145,5)    # time scale
data = np.sin(np.arange(20)).reshape(5,4)    # 4 time-dependent series

time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [20]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [21]:
# index of the max for each series

ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1])

In [22]:
# time corresponding to the maxima
time_max = time[ind]
data_max = data[ind, range(data.shape[1])]

time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [23]:
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [24]:
np.all(data_max == data.max(axis=0))

True

In [25]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])