## Linear Algebra

* this document warns that it is a work in progress. Currently there appears to only be one section.

### Simple Array Operations

* See linalg.py in numpy folder (whatever that means?)

In [1]:
import numpy as np

a = np.array([[1.0,2.0],[3.0,4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [2]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [3]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [4]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [5]:
j = np.array([[0.0,-1.0],[1.0,0.0]])
j@j

array([[-1.,  0.],
       [ 0., -1.]])

In [6]:
np.trace(u)

2.0

In [7]:
y = np.array([[5.],[7.]])
np.linalg.solve(a,y)

array([[-3.],
       [ 4.]])

In [8]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))